Update api.yml

diff --git a/.github/workflows/api.yml b/.github/workflows/api.yml
--- a/.github/workflows/api.yml
+++ b/.github/workflows/api.yml
@@ -16,7 +16,7 @@ jobs:
       - name: Fetch data from URL with retries
         run: |
           for i in {1..5}; do
-            curl -L -o data.json "https://script.google.com/macros/s/AKfycbzhonJLTBbNmwApISi4-1j1iwAdFu56Gfxawnuzt1vovmu3TOReFCgQLel9GzfZNxVyVA/exec" && break || echo "Attempt $i failed! Retrying..."
+            curl -L -o api.json "https://script.google.com/macros/s/AKfycbzhonJLTBbNmwApISi4-1j1iwAdFu56Gfxawnuzt1vovmu3TOReFCgQLel9GzfZNxVyVA/exec" && break || echo "Attempt $i failed! Retrying..."
             sleep 5  # 等待 5 秒再重試
           done
         continue-on-error: true
@@ -25,6 +25,6 @@ jobs:
         run: |
           git config --local user.name "github-actions"
           git config --local user.email "actions@github.com"
-          git add data.json
-          git commit -m "Update data.json" || echo "No changes to commit"
+          git add api.json
+          git commit -m "Update api.json" || echo "No changes to commit"
           git push
