Change CSV data fetch range to include column G
Updated the CSV data fetch range from A:F to A:G.

diff --git a/.github/workflows/cc_data.yml b/.github/workflows/cc_data.yml
--- a/.github/workflows/cc_data.yml
+++ b/.github/workflows/cc_data.yml
@@ -14,7 +14,7 @@ jobs:
       - name: Fetch CSV data from URL with retries
         run: |
           for i in {1..5}; do
-            curl -L -o data.csv "https://docs.google.com/spreadsheets/d/1RPaDMxpjIJIW3YmzaiXnH8wbFumqSELtiSx2rigP82U/gviz/tq?tqx=out:csv&sheet=cc_data&range=A:F" && break || echo "Attempt $i failed! Retrying..."
+            curl -L -o data.csv "https://docs.google.com/spreadsheets/d/1RPaDMxpjIJIW3YmzaiXnH8wbFumqSELtiSx2rigP82U/gviz/tq?tqx=out:csv&sheet=cc_data&range=A:G" && break || echo "Attempt $i failed! Retrying..."
             sleep 5  # 等待 5 秒再重试
           done
         continue-on-error: true
