Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,7 +16,7 @@ jobs:
       - name: Fetch CSV data from URL with retries
         run: |
           for i in {1..5}; do
-            curl -L -o data.csv "https://docs.google.com/spreadsheets/d/16Qt-BoIr6xezy8U34e55nzej7p5tzokriaArQNJF8bI/gviz/tq?tqx=out:csv&amp;sheet=RAW_DATA" && break || echo "Attempt $i failed! Retrying..."
+            curl -L -o data.csv "https://docs.google.com/spreadsheets/d/1xtsk0sCS-EjcA_wMBRXW0YVoGdw-jrPHBM1ooLgnC2w/gviz/tq?tqx=out:csv&sheet=Sheet1" && break || echo "Attempt $i failed! Retrying..."
             sleep 5  # 等待 5 秒再重試
           done
         continue-on-error: true
