Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,13 +13,27 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Fetch data from URL with retries
+      - name: Fetch CSV data from URL with retries
         run: |
           for i in {1..5}; do
-            curl -L -o data.json "https://script.google.com/macros/s/AKfycby_ssZQyVKzA57TBvApvqEsHrRMMx0JH3W3tcAIAIPLRLI-9t29U1NVoLU-ve3EgbDB/exec" && break || echo "Attempt $i failed! Retrying..."
+            curl -L -o data.csv "https://docs.google.com/spreadsheets/d/e/2PACX-1vQeuc6CXld1rCJILV8jGYqlV_8vZ9pJFswnrYAGH5QGhL2VQWGw7V27EoXZ9_a5F9Egnhm8yVsYLHaM/pub?gid=0&single=true&output=csv" && break || echo "Attempt $i failed! Retrying..."
             sleep 5  # 等待 5 秒再重試
           done
         continue-on-error: true
+
+      - name: Convert CSV to JSON
+        run: |
+          if [ -f data.csv ]; then
+            # 使用 jq 將 CSV 轉換為 JSON
+            # 需要安裝 jq
+            sudo apt-get install jq
+            # 使用 csvtojson 工具
+            npm install -g csvtojson
+            csvtojson data.csv > data.json
+          else
+            echo "data.csv not found!"
+            exit 1
+          fi
 
       - name: Commit and push changes
         run: |
