Update risk_age_group.yml

diff --git a/.github/workflows/risk_age_group.yml b/.github/workflows/risk_age_group.yml
--- a/.github/workflows/risk_age_group.yml
+++ b/.github/workflows/risk_age_group.yml
@@ -16,7 +16,7 @@ jobs:
       - name: Fetch CSV data from URL with retries
         run: |
           for i in {1..5}; do
-            curl -L -o data.csv "https://docs.google.com/spreadsheets/d/e/2PACX-1vRJ-iEq5K4CUbqtA6N21WDY8r_Fqk3Kvnw2Ks9l0jr0g31tQxEj_p1g9a23ambhG9qBtRbh_GepgiI2/pub?gid=0&single=true&output=csv&range=A9:D16" && break || echo "Attempt $i failed! Retrying..."
+            curl -L -o data.csv "https://docs.google.com/spreadsheets/d/1qxiiv89Mt7DTYAZAEqeq-3eTmtGtgyCkphwlWY0O9ao/gviz/tq?tqx=out:csv&sheet=rawData&range=A9:D16" && break || echo "Attempt $i failed! Retrying..."
             sleep 5  # 等待 5 秒再重试
           done
         continue-on-error: true
