Update yyyy_death.yml

diff --git a/.github/workflows/yyyy_death.yml b/.github/workflows/yyyy_death.yml
--- a/.github/workflows/yyyy_death.yml
+++ b/.github/workflows/yyyy_death.yml
@@ -16,7 +16,7 @@ jobs:
       - name: Fetch CSV data from URL with retries
         run: |
           for i in {1..5}; do
-            curl -L -o data.csv "https://docs.google.com/spreadsheets/d/1ijFymc6wrW9a4NfCctX9rroGIR808oKZDQzehAlSqAs/gviz/tq?tqx=out:csv&sheet=yyyy_death&range=A:N" && break || echo "Attempt $i failed! Retrying..."
+            curl -L -o data.csv "https://docs.google.com/spreadsheets/d/1RPaDMxpjIJIW3YmzaiXnH8wbFumqSELtiSx2rigP82U/gviz/tq?tqx=out:csv&sheet=yyyy_death&range=A:N" && break || echo "Attempt $i failed! Retrying..."
             sleep 5  # 等待 5 秒再重试
           done
         continue-on-error: true
